### ISSUE TITLE
ValidationError due to blank status

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/openapi2crd#1]
Generated YAMLs include a blank status structure:
```yaml
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
```

This causes errors on some kubectl versions:
```
error: error validating ".": error validating data: ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionStatus; if you choose to ignore these errors, turn validation off with --validate=false
```
